# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-drift_detection_function',
                'doc_host': 'https://KamaleshMS.github.io',
                'git_url': 'https://github.com/KamaleshMS/nbdev-drift_detection_function',
                'lib_path': 'nbdev_drift_detection_function'},
  'syms': { 'nbdev_drift_detection_function.Data_Drift_Function': { 'nbdev_drift_detection_function.Data_Drift_Function.data_drift_test_selection': ( 'data_drift_function.html#data_drift_test_selection',
                                                                                                                                                      'nbdev_drift_detection_function/Data_Drift_Function.py'),
                                                                    'nbdev_drift_detection_function.Data_Drift_Function.detect_drift': ( 'data_drift_function.html#detect_drift',
                                                                                                                                         'nbdev_drift_detection_function/Data_Drift_Function.py'),
                                                                    'nbdev_drift_detection_function.Data_Drift_Function.run_data_drift_detection': ( 'data_drift_function.html#run_data_drift_detection',
                                                                                                                                                     'nbdev_drift_detection_function/Data_Drift_Function.py')}}}
