# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-drift_detection_function',
                'doc_host': 'https://KamaleshMS.github.io',
                'git_url': 'https://github.com/KamaleshMS/nbdev-drift_detection_function',
                'lib_path': 'nbdev_drift_detection_function'},
  'syms': { 'nbdev_drift_detection_function.core': { 'nbdev_drift_detection_function.core.foo': ( 'core.html#foo',
                                                                                                  'nbdev_drift_detection_function/core.py')}}}
